# -*- coding: utf-8 -*-

"""
    lyftapilib.lyft_api_client

    This file was automatically generated by APIMATIC BETA v2.0 on 11/14/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class LyftAPIClient(object):

    @lazy_property
    def public(self):
        return PublicController()

    @lazy_property
    def user(self):
        return UserController()

    @lazy_property
    def sandbox(self):
        return SandboxController()


    def __init__(self, 
                 o_auth_access_token = None):

        if o_auth_access_token != None:
            Configuration.o_auth_access_token = o_auth_access_token


