# -*- coding: utf-8 -*-

"""
    lyftapilib.models.can_cancel_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""

class CanCancelEnum(object):

    """Implementation of the 'CanCancel' enum.

    The array of actors who may cancel the ride at this point

    Attributes:
        DRIVER: TODO: type description here.
        PASSENGER: TODO: type description here.
        DISPATCHER: TODO: type description here.

    """

    DRIVER = 'driver'

    PASSENGER = 'passenger'

    DISPATCHER = 'dispatcher'

