# -*- coding: utf-8 -*-

"""
    lyftapilib.models.cancellation_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class CancellationRequest(BaseModel):

    """Implementation of the 'CancellationRequest' model.

    TODO: type model description here.

    Attributes:
        cancel_confirmation_token (string): Token affirming the user accepts
            the cancellation fee. Required if a cancellation fee is in
            effect.

    """

    def __init__(self, 
                 cancel_confirmation_token = None):
        """Constructor for the CancellationRequest class"""
        
        # Initialize members of the class
        self.cancel_confirmation_token = cancel_confirmation_token

        # Create a mapping from Model property names to API property names
        self.names = {
            "cancel_confirmation_token" : "cancel_confirmation_token",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            cancel_confirmation_token = dictionary.get("cancel_confirmation_token")
            # Return an object of this model
            return cls(cancel_confirmation_token)
