# -*- coding: utf-8 -*-

"""
    lyftapilib.models.cancellation_cost
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class CancellationCost(BaseModel):

    """Implementation of the 'CancellationCost' model.

    TODO: type model description here.

    Attributes:
        amount (int): Total price of the ride
        currency (string): The ISO 4217 currency code for the amount (e.g.
            USD)
        description (string): The description for the cost
        token (string): Token used to confirm the fee when cancelling a
            request
        token_duration (int): How long, in seconds, before the token expires

    """

    def __init__(self, 
                 amount = None,
                 currency = None,
                 description = None,
                 token = None,
                 token_duration = None):
        """Constructor for the CancellationCost class"""
        
        # Initialize members of the class
        self.amount = amount
        self.currency = currency
        self.description = description
        self.token = token
        self.token_duration = token_duration

        # Create a mapping from Model property names to API property names
        self.names = {
            "amount" : "amount",
            "currency" : "currency",
            "description" : "description",
            "token" : "token",
            "token_duration" : "token_duration",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            amount = dictionary.get("amount")
            currency = dictionary.get("currency")
            description = dictionary.get("description")
            token = dictionary.get("token")
            token_duration = dictionary.get("token_duration")
            # Return an object of this model
            return cls(amount,
                       currency,
                       description,
                       token,
                       token_duration)
