# -*- coding: utf-8 -*-

"""
    lyftapilib.models.charge
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class Charge(BaseModel):

    """Implementation of the 'Charge' model.

    TODO: type model description here.

    Attributes:
        amount (int): The line item amount
        currency (string): The currency for the amount
        payment_method (string): The payment method display name.

    """

    def __init__(self, 
                 amount = None,
                 currency = None,
                 payment_method = None):
        """Constructor for the Charge class"""
        
        # Initialize members of the class
        self.amount = amount
        self.currency = currency
        self.payment_method = payment_method

        # Create a mapping from Model property names to API property names
        self.names = {
            "amount" : "amount",
            "currency" : "currency",
            "payment_method" : "payment_method",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            amount = dictionary.get("amount")
            currency = dictionary.get("currency")
            payment_method = dictionary.get("payment_method")
            # Return an object of this model
            return cls(amount,
                       currency,
                       payment_method)
