# -*- coding: utf-8 -*-

"""
    lyftapilib.models.cost_estimate_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .cost_estimate import CostEstimate
from .base_model import BaseModel

class CostEstimateResponse(BaseModel):

    """Implementation of the 'CostEstimateResponse' model.

    TODO: type model description here.

    Attributes:
        cost_estimates (list of CostEstimate): TODO: type description here.

    """

    def __init__(self, 
                 cost_estimates = None):
        """Constructor for the CostEstimateResponse class"""
        
        # Initialize members of the class
        self.cost_estimates = cost_estimates

        # Create a mapping from Model property names to API property names
        self.names = {
            "cost_estimates" : "cost_estimates",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            cost_estimates = None
            if dictionary.get("cost_estimates") != None:
                cost_estimates = list()
                for structure in dictionary.get("cost_estimates"):
                    cost_estimates.append(CostEstimate.from_dictionary(structure))
            # Return an object of this model
            return cls(cost_estimates)
