# -*- coding: utf-8 -*-

"""
    lyftapilib.models.driver_detail
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class DriverDetail(BaseModel):

    """Implementation of the 'DriverDetail' model.

    TODO: type model description here.

    Attributes:
        first_name (string): The driver's first name
        phone_number (string): The driver's contact phone number. Must be
            E.164 formatted.
        rating (string): The driver's rating based in 0-5 scale
        image_url (string): The driver's image url

    """

    def __init__(self, 
                 first_name = None,
                 phone_number = None,
                 rating = None,
                 image_url = None):
        """Constructor for the DriverDetail class"""
        
        # Initialize members of the class
        self.first_name = first_name
        self.phone_number = phone_number
        self.rating = rating
        self.image_url = image_url

        # Create a mapping from Model property names to API property names
        self.names = {
            "first_name" : "first_name",
            "phone_number" : "phone_number",
            "rating" : "rating",
            "image_url" : "image_url",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            first_name = dictionary.get("first_name")
            phone_number = dictionary.get("phone_number")
            rating = dictionary.get("rating")
            image_url = dictionary.get("image_url")
            # Return an object of this model
            return cls(first_name,
                       phone_number,
                       rating,
                       image_url)
