# -*- coding: utf-8 -*-

"""
    lyftapilib.models.error_detail
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class ErrorDetail(BaseModel):

    """Implementation of the 'ErrorDetail' model.

    An object with a single key-value pair, where the key is the name of the
    invalid parameter, and the value is a description of the error.

    Attributes:
        field_name (string): description of the error

    """

    def __init__(self, 
                 field_name = None):
        """Constructor for the ErrorDetail class"""
        
        # Initialize members of the class
        self.field_name = field_name

        # Create a mapping from Model property names to API property names
        self.names = {
            "field_name" : "field_name",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            field_name = dictionary.get("field_name")
            # Return an object of this model
            return cls(field_name)
