# -*- coding: utf-8 -*-

"""
    lyftapilib.models.eta_estimate_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .eta import Eta
from .base_model import BaseModel

class EtaEstimateResponse(BaseModel):

    """Implementation of the 'EtaEstimateResponse' model.

    TODO: type model description here.

    Attributes:
        eta_estimates (list of Eta): TODO: type description here.

    """

    def __init__(self, 
                 eta_estimates = None):
        """Constructor for the EtaEstimateResponse class"""
        
        # Initialize members of the class
        self.eta_estimates = eta_estimates

        # Create a mapping from Model property names to API property names
        self.names = {
            "eta_estimates" : "eta_estimates",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            eta_estimates = None
            if dictionary.get("eta_estimates") != None:
                eta_estimates = list()
                for structure in dictionary.get("eta_estimates"):
                    eta_estimates.append(Eta.from_dictionary(structure))
            # Return an object of this model
            return cls(eta_estimates)
