# -*- coding: utf-8 -*-

"""
    lyftapilib.models.line_item
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class LineItem(BaseModel):

    """Implementation of the 'LineItem' model.

    TODO: type model description here.

    Attributes:
        mtype (string): The line item display name for a charge item
        amount (int): The line item amount
        currency (string): The currency for the amount

    """

    def __init__(self, 
                 mtype = None,
                 amount = None,
                 currency = None):
        """Constructor for the LineItem class"""
        
        # Initialize members of the class
        self.mtype = mtype
        self.amount = amount
        self.currency = currency

        # Create a mapping from Model property names to API property names
        self.names = {
            "mtype" : "type",
            "amount" : "amount",
            "currency" : "currency",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            mtype = dictionary.get("type")
            amount = dictionary.get("amount")
            currency = dictionary.get("currency")
            # Return an object of this model
            return cls(mtype,
                       amount,
                       currency)
