# -*- coding: utf-8 -*-

"""
    lyftapilib.models.location
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class Location(BaseModel):

    """Implementation of the 'Location' model.

    TODO: type model description here.

    Attributes:
        lat (float): The latitude component of a location
        lng (float): The longitude component of a location
        address (string): A human readable address at/near the given location

    """

    def __init__(self, 
                 lat = None,
                 lng = None,
                 address = None):
        """Constructor for the Location class"""
        
        # Initialize members of the class
        self.lat = lat
        self.lng = lng
        self.address = address

        # Create a mapping from Model property names to API property names
        self.names = {
            "lat" : "lat",
            "lng" : "lng",
            "address" : "address",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            lat = dictionary.get("lat")
            lng = dictionary.get("lng")
            address = dictionary.get("address")
            # Return an object of this model
            return cls(lat,
                       lng,
                       address)
