# -*- coding: utf-8 -*-

"""
    lyftapilib.models.nearby_drivers_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .nearby_drivers_by_ride_type import NearbyDriversByRideType
from .base_model import BaseModel

class NearbyDriversResponse(BaseModel):

    """Implementation of the 'NearbyDriversResponse' model.

    TODO: type model description here.

    Attributes:
        nearby_drivers (list of NearbyDriversByRideType): TODO: type
            description here.

    """

    def __init__(self, 
                 nearby_drivers = None):
        """Constructor for the NearbyDriversResponse class"""
        
        # Initialize members of the class
        self.nearby_drivers = nearby_drivers

        # Create a mapping from Model property names to API property names
        self.names = {
            "nearby_drivers" : "nearby_drivers",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            nearby_drivers = None
            if dictionary.get("nearby_drivers") != None:
                nearby_drivers = list()
                for structure in dictionary.get("nearby_drivers"):
                    nearby_drivers.append(NearbyDriversByRideType.from_dictionary(structure))
            # Return an object of this model
            return cls(nearby_drivers)
