# -*- coding: utf-8 -*-

"""
    lyftapilib.models.nearby_driver
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .lat_lng import LatLng
from .base_model import BaseModel

class NearbyDriver(BaseModel):

    """Implementation of the 'NearbyDriver' model.

    TODO: type model description here.

    Attributes:
        locations (list of LatLng): the lastest recorded driver locations up
            to 5 sorted in chronological order.

    """

    def __init__(self, 
                 locations = None):
        """Constructor for the NearbyDriver class"""
        
        # Initialize members of the class
        self.locations = locations

        # Create a mapping from Model property names to API property names
        self.names = {
            "locations" : "locations",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            locations = None
            if dictionary.get("locations") != None:
                locations = list()
                for structure in dictionary.get("locations"):
                    locations.append(LatLng.from_dictionary(structure))
            # Return an object of this model
            return cls(locations)
