# -*- coding: utf-8 -*-

"""
    lyftapilib.models.pickup_dropoff_location
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
import dateutil.parser
from .base_model import BaseModel

class PickupDropoffLocation(BaseModel):

    """Implementation of the 'PickupDropoffLocation' model.

    TODO: type model description here.

    Attributes:
        time (DateTime): Server time when the location object is created

    """

    def __init__(self, 
                 time = None):
        """Constructor for the PickupDropoffLocation class"""
        
        # Initialize members of the class
        self.time = time

        # Create a mapping from Model property names to API property names
        self.names = {
            "time" : "time",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            time = dateutil.parser.parse(dictionary.get("time")) if dictionary.get("time") else None
            # Return an object of this model
            return cls(time)
