# -*- coding: utf-8 -*-

"""
    lyftapilib.models.profile
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class Profile(BaseModel):

    """Implementation of the 'Profile' model.

    Represents the general information about a user.

    Attributes:
        id (string): The unique ID of this user

    """

    def __init__(self, 
                 id = None):
        """Constructor for the Profile class"""
        
        # Initialize members of the class
        self.id = id

        # Create a mapping from Model property names to API property names
        self.names = {
            "id" : "id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            id = dictionary.get("id")
            # Return an object of this model
            return cls(id)
