# -*- coding: utf-8 -*-

"""
    lyftapilib.models.rating_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .tip_params import TipParams
from .base_model import BaseModel

class RatingRequest(BaseModel):

    """Implementation of the 'RatingRequest' model.

    Rating and optional feedback and tip

    Attributes:
        rating (int): The passenger's rating of this ride from 1 to 5
        feedback (string): The passenger's written feedback about this ride
        tip (TipParams): Tip amount in minor units and tip currency

    """

    def __init__(self, 
                 rating = None,
                 feedback = None,
                 tip = None):
        """Constructor for the RatingRequest class"""
        
        # Initialize members of the class
        self.rating = rating
        self.feedback = feedback
        self.tip = tip

        # Create a mapping from Model property names to API property names
        self.names = {
            "rating" : "rating",
            "feedback" : "feedback",
            "tip" : "tip",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            rating = dictionary.get("rating")
            feedback = dictionary.get("feedback")
            tip = TipParams.from_dictionary(dictionary.get("tip")) if dictionary.get("tip") else None
            # Return an object of this model
            return cls(rating,
                       feedback,
                       tip)
