# -*- coding: utf-8 -*-

"""
    lyftapilib.models.rides_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .ride_detail import RideDetail
from .base_model import BaseModel

class RidesResponse(BaseModel):

    """Implementation of the 'RidesResponse' model.

    TODO: type model description here.

    Attributes:
        ride_history (list of RideDetail): TODO: type description here.

    """

    def __init__(self, 
                 ride_history = None):
        """Constructor for the RidesResponse class"""
        
        # Initialize members of the class
        self.ride_history = ride_history

        # Create a mapping from Model property names to API property names
        self.names = {
            "ride_history" : "ride_history",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ride_history = None
            if dictionary.get("ride_history") != None:
                ride_history = list()
                for structure in dictionary.get("ride_history"):
                    ride_history.append(RideDetail.from_dictionary(structure))
            # Return an object of this model
            return cls(ride_history)
