# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .location import Location
from .passenger_detail import PassengerDetail
from .base_model import BaseModel

class RideRequest(BaseModel):

    """Implementation of the 'RideRequest' model.

    Minimal set of ride details

    Attributes:
        ride_id (string): The ID of the requested ride
        status (RideStatusEnum): The current status of the ride
        origin (Location): The *requested* location for passenger pickup
        destination (Location): The *requested* location for passenger drop
            off
        passenger (PassengerDetail): TODO: type description here.

    """

    def __init__(self, 
                 ride_id = None,
                 status = None,
                 origin = None,
                 destination = None,
                 passenger = None):
        """Constructor for the RideRequest class"""
        
        # Initialize members of the class
        self.ride_id = ride_id
        self.status = status
        self.origin = origin
        self.destination = destination
        self.passenger = passenger

        # Create a mapping from Model property names to API property names
        self.names = {
            "ride_id" : "ride_id",
            "status" : "status",
            "origin" : "origin",
            "destination" : "destination",
            "passenger" : "passenger",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ride_id = dictionary.get("ride_id")
            status = dictionary.get("status")
            origin = Location.from_dictionary(dictionary.get("origin")) if dictionary.get("origin") else None
            destination = Location.from_dictionary(dictionary.get("destination")) if dictionary.get("destination") else None
            passenger = PassengerDetail.from_dictionary(dictionary.get("passenger")) if dictionary.get("passenger") else None
            # Return an object of this model
            return cls(ride_id,
                       status,
                       origin,
                       destination,
                       passenger)
