# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_types_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .ride_type import RideType
from .base_model import BaseModel

class RideTypesResponse(BaseModel):

    """Implementation of the 'RideTypesResponse' model.

    TODO: type model description here.

    Attributes:
        ride_types (list of RideType): TODO: type description here.

    """

    def __init__(self, 
                 ride_types = None):
        """Constructor for the RideTypesResponse class"""
        
        # Initialize members of the class
        self.ride_types = ride_types

        # Create a mapping from Model property names to API property names
        self.names = {
            "ride_types" : "ride_types",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ride_types = None
            if dictionary.get("ride_types") != None:
                ride_types = list()
                for structure in dictionary.get("ride_types"):
                    ride_types.append(RideType.from_dictionary(structure))
            # Return an object of this model
            return cls(ride_types)
