# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .location import Location
from .base_model import BaseModel

class Ride(BaseModel):

    """Implementation of the 'Ride' model.

    Represents a requested, ongoing, or finished Lyft ride

    Attributes:
        ride_type (RideTypeEnum): The ID of the ride type
        origin (Location): The *requested* location for passenger pickup
        ride_id (string): The unique ID of this ride
        destination (Location): The *requested* location for passenger drop
            off
        primetime_confirmation_token (string): A token that confirms the user
            has accepted current primetime charges

    """

    def __init__(self, 
                 ride_type = None,
                 origin = None,
                 ride_id = None,
                 destination = None,
                 primetime_confirmation_token = None):
        """Constructor for the Ride class"""
        
        # Initialize members of the class
        self.ride_type = ride_type
        self.origin = origin
        self.ride_id = ride_id
        self.destination = destination
        self.primetime_confirmation_token = primetime_confirmation_token

        # Create a mapping from Model property names to API property names
        self.names = {
            "ride_type" : "ride_type",
            "origin" : "origin",
            "ride_id" : "ride_id",
            "destination" : "destination",
            "primetime_confirmation_token" : "primetime_confirmation_token",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ride_type = dictionary.get("ride_type")
            origin = Location.from_dictionary(dictionary.get("origin")) if dictionary.get("origin") else None
            ride_id = dictionary.get("ride_id")
            destination = Location.from_dictionary(dictionary.get("destination")) if dictionary.get("destination") else None
            primetime_confirmation_token = dictionary.get("primetime_confirmation_token")
            # Return an object of this model
            return cls(ride_type,
                       origin,
                       ride_id,
                       destination,
                       primetime_confirmation_token)
