# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_location
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class RideLocation(BaseModel):

    """Implementation of the 'RideLocation' model.

    TODO: type model description here.

    Attributes:
        eta_seconds (int): Estimated seconds for a driver to pickup or reach
            destination based on ride state

    """

    def __init__(self, 
                 eta_seconds = None):
        """Constructor for the RideLocation class"""
        
        # Initialize members of the class
        self.eta_seconds = eta_seconds

        # Create a mapping from Model property names to API property names
        self.names = {
            "eta_seconds" : "eta_seconds",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            eta_seconds = dictionary.get("eta_seconds")
            # Return an object of this model
            return cls(eta_seconds)
