# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_profile_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""

class RideProfileEnum(object):

    """Implementation of the 'RideProfileEnum' enum.

    The payment profile which the user has picked for the ride

    Attributes:
        PERSONAL: TODO: type description here.
        BUSINESS: TODO: type description here.

    """

    PERSONAL = 'personal'

    BUSINESS = 'business'

