# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""

class RideTypeEnum(object):

    """Implementation of the 'RideTypeEnum' enum.

    The ID of the ride type

    Attributes:
        LYFT: TODO: type description here.
        LYFT_LINE: TODO: type description here.
        LYFT_PLUS: TODO: type description here.
        LYFT_SUV: TODO: type description here.

    """

    LYFT = 'lyft'

    LYFT_LINE = 'lyft_line'

    LYFT_PLUS = 'lyft_plus'

    LYFT_SUV = 'lyft_suv'

