# -*- coding: utf-8 -*-

"""
    lyftapilib.models.ride_status_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""

class RideStatusEnum(object):

    """Implementation of the 'RideStatusEnum' enum.

    The current status of the ride

    Attributes:
        PENDING: TODO: type description here.
        ACCEPTED: TODO: type description here.
        ARRIVED: TODO: type description here.
        PICKEDUP: TODO: type description here.
        DROPPEDOFF: TODO: type description here.
        CANCELED: TODO: type description here.
        UNKNOWN: TODO: type description here.

    """

    PENDING = 'pending'

    ACCEPTED = 'accepted'

    ARRIVED = 'arrived'

    PICKEDUP = 'pickedUp'

    DROPPEDOFF = 'droppedOff'

    CANCELED = 'canceled'

    UNKNOWN = 'unknown'

