# -*- coding: utf-8 -*-

"""
    lyftapilib.models.sandbox_ride_update
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class SandboxRideUpdate(BaseModel):

    """Implementation of the 'SandboxRideUpdate' model.

    Response when a sandbox ride is propagated between states

    Attributes:
        ride_id (string): The ID of the ride
        status (RideStatusEnum): The current status of the ride

    """

    def __init__(self, 
                 ride_id = None,
                 status = None):
        """Constructor for the SandboxRideUpdate class"""
        
        # Initialize members of the class
        self.ride_id = ride_id
        self.status = status

        # Create a mapping from Model property names to API property names
        self.names = {
            "ride_id" : "ride_id",
            "status" : "status",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ride_id = dictionary.get("ride_id")
            status = dictionary.get("status")
            # Return an object of this model
            return cls(ride_id,
                       status)
