# -*- coding: utf-8 -*-

"""
    lyftapilib.models.tip_params
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class TipParams(BaseModel):

    """Implementation of the 'TipParams' model.

    TODO: type model description here.

    Attributes:
        amount (int): A tip for the driver in cents. To be charged to the
            user's default charge account.
        currency (string): The currency in which you want to tip. e.g. USD

    """

    def __init__(self, 
                 amount = None,
                 currency = None):
        """Constructor for the TipParams class"""
        
        # Initialize members of the class
        self.amount = amount
        self.currency = currency

        # Create a mapping from Model property names to API property names
        self.names = {
            "amount" : "amount",
            "currency" : "currency",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            amount = dictionary.get("amount")
            currency = dictionary.get("currency")
            # Return an object of this model
            return cls(amount,
                       currency)
