# -*- coding: utf-8 -*-

"""
    lyftapilib.models.user_detail
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class UserDetail(BaseModel):

    """Implementation of the 'UserDetail' model.

    TODO: type model description here.

    Attributes:
        first_name (string): The passenger's first name
        image_url (string): The passenger's profile image
        rating (string): The passenger's rating

    """

    def __init__(self, 
                 first_name = None,
                 image_url = None,
                 rating = None):
        """Constructor for the UserDetail class"""
        
        # Initialize members of the class
        self.first_name = first_name
        self.image_url = image_url
        self.rating = rating

        # Create a mapping from Model property names to API property names
        self.names = {
            "first_name" : "first_name",
            "image_url" : "image_url",
            "rating" : "rating",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            first_name = dictionary.get("first_name")
            image_url = dictionary.get("image_url")
            rating = dictionary.get("rating")
            # Return an object of this model
            return cls(first_name,
                       image_url,
                       rating)
