# -*- coding: utf-8 -*-

"""
    lyftapilib.models.vehicle_detail
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from .base_model import BaseModel

class VehicleDetail(BaseModel):

    """Implementation of the 'VehicleDetail' model.

    TODO: type model description here.

    Attributes:
        make (string): The vehicle's maker
        model (string): The vehicle's model
        year (int): The vehicle's model year
        license_plate (string): The vehicle's license plate
        license_plate_state (string): The vehicle's license plate state
        color (string): The vehicle's color
        image_url (string): The vehicle's image url

    """

    def __init__(self, 
                 make = None,
                 model = None,
                 year = None,
                 license_plate = None,
                 license_plate_state = None,
                 color = None,
                 image_url = None):
        """Constructor for the VehicleDetail class"""
        
        # Initialize members of the class
        self.make = make
        self.model = model
        self.year = year
        self.license_plate = license_plate
        self.license_plate_state = license_plate_state
        self.color = color
        self.image_url = image_url

        # Create a mapping from Model property names to API property names
        self.names = {
            "make" : "make",
            "model" : "model",
            "year" : "year",
            "license_plate" : "license_plate",
            "license_plate_state" : "license_plate_state",
            "color" : "color",
            "image_url" : "image_url",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            make = dictionary.get("make")
            model = dictionary.get("model")
            year = dictionary.get("year")
            license_plate = dictionary.get("license_plate")
            license_plate_state = dictionary.get("license_plate_state")
            color = dictionary.get("color")
            image_url = dictionary.get("image_url")
            # Return an object of this model
            return cls(make,
                       model,
                       year,
                       license_plate,
                       license_plate_state,
                       color,
                       image_url)
