# -*- coding: utf-8 -*-

"""
    lyftapilib.models.cancellation_cost_error_exception
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
"""
from ..api_helper import APIHelper
from .api_exception import APIException
from ..models.error_detail import ErrorDetail

class CancellationCostErrorException(APIException):
    def __init__(self, reason, context):
        """Constructor for the CancellationCostErrorException class
        
        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.            
            context (HttpContext):  The HttpContext of the API call.
        
        """        
        super(CancellationCostErrorException, self).__init__(reason, context)
        dictionary = APIHelper.json_deserialize(self.context.response.raw_body)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        """
        self.error = dictionary.get("error")
        self.error_detail = None
        if dictionary.get("error_detail") != None:
            self.error_detail = list()
            for structure in dictionary.get("error_detail"):
                self.error_detail.append(ErrorDetail.from_dictionary(structure))
        self.error_description = dictionary.get("error_description")